version: 2

sources:
  - name: destination_db
    description: "Raw data from the destination PostgreSQL database."
    database: destination_db
    schema: public
    tables:
      - name: films
        description: "List of films."
      - name: actors
        description: "List of actors."
      - name: film_actors
        description: "Mapping between films and actors."


# sources:
#   - name: name_of the source
#     schema: name_of_the_schema
#     quoting:
#       database: false
#       schema: false
#       identifier: false
#     loader: stitch
#     tables:
#       - name: name_of_table1
#       - name: name_of_table2